### PR TITLE
Move Code Annotation Pane to Activity Bar

### PR DESCRIPTION
**Pull request by natandias**
I added "viewsContainers" on package.json, real changes start at line 171 and ends at line 187, the rest is just formatting.

### CODE REVIEW

**Comment by thamara** [comment]
Wow! That was much simpler than I would expected! Thank you a lot! 
I'm just going to do some manual tests, but looks awesome!

**Review by thamara — APPROVED** [review]

**Comment by thamara** [comment]
Indeed looks awesome! Thank you a lot for the contribution!

**Comment by thamara** [comment]
Closes #8.

**Comment by natandias** [comment]
Glad to be of help!

**Pull request merged**
